# **DATA SCIENCE PROGRAMMING MIDTERM EXAMS**

**Part 1: Data Cleaning**

In [ ]:
import pandas as pd

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving student_scores.csv to student_scores (1).csv

In [ ]:
import io
ScoresData = pd.read_csv(io.BytesIO(uploaded['student_scores (1).csv']))

In [ ]:
print("\nStudent Scores Dataset:")
display(ScoresData.head())

Student Scores Dataset:

,id,name,gender,birth_date,math_score,english_score,science_score,address,guardian_contact,guardian_name
0,1,James Schneider,Male,2007-02-23,88.0,76.0,NaN,"USCGC Flores, FPO AA 67418",NaN,NaN
1,2,Kristina Weeks,Male,2008-07-03,NaN,75.0,70.0,"54202 Daniel Spur, East Jennifer, ID 59341",NaN,NaN
2,3,Danielle Norman,Female,2009-01-02,87.0,NaN,86.0,"USS Richardson, FPO AE 76519",NaN,NaN
3,4,Susan Morgan,Female,2008-12-06,97.0,73.0,NaN,"21808 Kendra Terrace Apt. 517, Barnettstad, SD...",NaN,Kenneth Jenkins
4,5,Erika Wilson,Female,2008-12-26,70.0,60.0,90.0,"187 Luke Plains Apt. 556, Nelsonport, VT 67229",NaN,NaN

In [ ]:
print("\nDataset Info:")
print(ScoresData.info())

Dataset Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                30 non-null     int64
 1   name              30 non-null     object
 2   gender            30 non-null     object
 3   birth_date        30 non-null     object
 4   math_score        24 non-null     float64
 5   english_score     25 non-null     float64
 6   science_score     23 non-null     float64
 7   address           30 non-null     object
 8   guardian_contact  11 non-null     object
 9   guardian_name     4 non-null      object
dtypes: float64(3), int64(1), object(6)
memory usage: 2.5+ KB
None

In [ ]:
print("\nStatistical Description:")
print(ScoresData.describe(include = 'all'))

Statistical Description:
               id             name gender  birth_date  math_score  \
count   30.000000               30     30          30   24.000000
unique        NaN               30      2          30         NaN
top           NaN  James Schneider   Male  2007-02-23         NaN
freq          NaN                1     15           1         NaN
mean    15.500000              NaN    NaN         NaN   80.458333
std      8.803408              NaN    NaN         NaN   10.709521
min      1.000000              NaN    NaN         NaN   60.000000
25%      8.250000              NaN    NaN         NaN   75.000000
50%     15.500000              NaN    NaN         NaN   81.000000
75%     22.750000              NaN    NaN         NaN   88.000000
max     30.000000              NaN    NaN         NaN   97.000000

        english_score  science_score                     address  \
count       25.000000      23.000000                          30
unique            NaN            NaN                          30
top               NaN            NaN  USCGC Flores, FPO AA 67418
freq              NaN            NaN                           1
mean        78.600000      78.652174                         NaN
std         10.242884      11.679853                         NaN
min         60.000000      61.000000                         NaN
25%         73.000000      69.000000                         NaN
50%         78.000000      78.000000                         NaN
75%         88.000000      88.000000                         NaN
max         96.000000      99.000000                         NaN

       guardian_contact    guardian_name
count                11                4
unique               11                4
top        474-999-7190  Kenneth Jenkins
freq                  1                1
mean                NaN              NaN
std                 NaN              NaN
min                 NaN              NaN
25%                 NaN              NaN
50%                 NaN              NaN
75%                 NaN              NaN
max                 NaN              NaN

In [ ]:
ScoresData['math_score'].fillna(ScoresData['math_score'].mean(), inplace = True)
ScoresData['english_score'].fillna(ScoresData['english_score'].mean(), inplace = True)
ScoresData['science_score'].fillna(ScoresData['science_score'].mean(), inplace = True)

<ipython-input-257-997284847>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  ScoresData['math_score'].fillna(ScoresData['math_score'].mean(), inplace = True)
<ipython-input-257-997284847>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  ScoresData['english_score'].fillna(ScoresData['english_score'].mean(), inplace = True)
<ipython-input-257-997284847>:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  ScoresData['science_score'].fillna(ScoresData['science_score'].mean(), inplace = True)

In [ ]:
duplicate_count = ScoresData.duplicated().sum()
print(f"Number of duplicate rows: {duplicate_count}")

Number of duplicate rows: 0

In [ ]:
ScoresData.drop(columns = ['address','guardian_contact', 'guardian_name'], inplace = True)
display(ScoresData.head())

explanation = """
I dropped the columns: address, guardian_contact, and guardian_name because my data solely focuses on the students grades.
The mentioned columns were not helpful in computing or encoding the students' grades for this data.
"""

print(explanation)

,id,name,gender,birth_date,math_score,english_score,science_score
0,1,James Schneider,Male,2007-02-23,88.000000,76.0,78.652174
1,2,Kristina Weeks,Male,2008-07-03,80.458333,75.0,70.000000
2,3,Danielle Norman,Female,2009-01-02,87.000000,78.6,86.000000
3,4,Susan Morgan,Female,2008-12-06,97.000000,73.0,78.652174
4,5,Erika Wilson,Female,2008-12-26,70.000000,60.0,90.000000

I dropped the columns: address, guardian_contact, and guardian_name because my data solely focuses on the students grades.
The mentioned columns were not helpful in computing or encoding the students' grades for this data.

In [ ]:
ScoresData.columns = ScoresData.columns.str.strip().str.lower().str.replace(' ', '_')

In [ ]:
print("\nCleaned Dataset Preview:")
display(ScoresData.head())

Cleaned Dataset Preview:

,id,name,gender,birth_date,math_score,english_score,science_score
0,1,James Schneider,Male,2007-02-23,88.000000,76.0,78.652174
1,2,Kristina Weeks,Male,2008-07-03,80.458333,75.0,70.000000
2,3,Danielle Norman,Female,2009-01-02,87.000000,78.6,86.000000
3,4,Susan Morgan,Female,2008-12-06,97.000000,73.0,78.652174
4,5,Erika Wilson,Female,2008-12-26,70.000000,60.0,90.000000

**Part 2: Data Type Conversion**

In [ ]:
ScoresData['birth_date'] = pd.to_datetime(ScoresData['birth_date'], errors = 'coerce')
display(ScoresData.head())

,id,name,gender,birth_date,math_score,english_score,science_score
0,1,James Schneider,Male,2007-02-23,88.000000,76.0,78.652174
1,2,Kristina Weeks,Male,2008-07-03,80.458333,75.0,70.000000
2,3,Danielle Norman,Female,2009-01-02,87.000000,78.6,86.000000
3,4,Susan Morgan,Female,2008-12-06,97.000000,73.0,78.652174
4,5,Erika Wilson,Female,2008-12-26,70.000000,60.0,90.000000

In [ ]:
object_columns = ScoresData.select_dtypes(include = 'object').columns
potential_numeric = {}

In [ ]:
for col in object_columns:
    try:
        ScoresData[col] = pd.to_numeric(ScoresData[col])
        potential_numeric[col] = 'converted to numeric'
    except ValueError:
        potential_numeric[col] = 'not converted (text data)'

In [ ]:
print("\nConversion Results:")
for col, status in potential_numeric.items():
    print(f"{col}: {status}")

print("\nUpdated Data Types:")
display(ScoresData.dtypes)

Conversion Results:
name: not converted (text data)
gender: not converted (text data)

Updated Data Types:

id                        int64
name                     object
gender                   object
birth_date       datetime64[ns]
math_score              float64
english_score           float64
science_score           float64
dtype: object

**Part 3: Scaling and Normalization**

In [ ]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler

In [ ]:
score_columns = ['math_score', 'english_score', 'science_score']

In [ ]:
minmax_scaler = MinMaxScaler()
ScoresData_minmax = ScoresData.copy()
ScoresData_minmax[score_columns] = minmax_scaler.fit_transform(ScoresData[score_columns])

display(ScoresData_minmax[score_columns].head())

   math_score  english_score  science_score
0    0.756757       0.444444       0.464531
1    0.552928       0.416667       0.236842
2    0.729730       0.516667       0.657895
3    1.000000       0.361111       0.464531
4    0.270270       0.000000       0.763158

In [ ]:
zscore_scaler = StandardScaler()
ScoresData_zscore = ScoresData.copy()
ScoresData_zscore[score_columns] = zscore_scaler.fit_transform(ScoresData[score_columns])

display(ScoresData_zscore[score_columns].head())

   math_score  english_score  science_score
0    0.804255      -0.283796       0.000000
1    0.000000      -0.392948      -0.865042
2    0.697614       0.000000       0.734634
3    1.764030      -0.611253       0.000000
4   -1.115293      -2.030232       1.134552

In [ ]:
print("Min-Max Normalized Scores:")
print(ScoresData_minmax[score_columns].head())

print("\nZ-score Standardized Scores:")
print(ScoresData_zscore[score_columns].head())

Min-Max Normalized Scores:
   math_score  english_score  science_score
0    0.756757       0.444444       0.464531
1    0.552928       0.416667       0.236842
2    0.729730       0.516667       0.657895
3    1.000000       0.361111       0.464531
4    0.270270       0.000000       0.763158

Z-score Standardized Scores:
   math_score  english_score  science_score
0    0.804255      -0.283796       0.000000
1    0.000000      -0.392948      -0.865042
2    0.697614       0.000000       0.734634
3    1.764030      -0.611253       0.000000
4   -1.115293      -2.030232       1.134552

**Part 4: Encoding Categorical Variables**

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
ScoresData_encoded = ScoresData.copy()

In [ ]:
label_encoder = LabelEncoder()
ScoresData_encoded['gender_encoded'] = label_encoder.fit_transform(ScoresData_encoded['gender'])

In [ ]:
print("Encoded DataFrame Preview:")
print(ScoresData_encoded.head())

Encoded DataFrame Preview:
   id             name  gender birth_date  math_score  english_score  \
0   1  James Schneider    Male 2007-02-23   88.000000           76.0
1   2   Kristina Weeks    Male 2008-07-03   80.458333           75.0
2   3  Danielle Norman  Female 2009-01-02   87.000000           78.6
3   4     Susan Morgan  Female 2008-12-06   97.000000           73.0
4   5     Erika Wilson  Female 2008-12-26   70.000000           60.0

   science_score  gender_encoded
0      78.652174               1
1      70.000000               1
2      86.000000               0
3      78.652174               0
4      90.000000               0

I used **Label Encoding** for the `gender` column since it only has two categories (Male and Female). This method is efficient for binary or ordinal data.

I **did not use One-Hot Encoding** because the other categorical columns ( `guardian_name`,`address`,`guardian_contact`) were dropped due to high missing values or uniqueness, which would make one-hot encoding impractical and add unnecessary complexity.

**Part 5: Feature Engineering**

In [ ]:
current_year = pd.Timestamp.now().year
ScoresData['birth_year'] = pd.DatetimeIndex(ScoresData['birth_date']).year
ScoresData['age'] = current_year - ScoresData['birth_year']

display(ScoresData[['birth_date', 'age']].head())

  birth_date  age
0 2007-02-23   18
1 2008-07-03   17
2 2009-01-02   16
3 2008-12-06   17
4 2008-12-26   17

In [ ]:
ScoresData['average_score'] = ScoresData[['math_score', 'english_score', 'science_score']].mean(axis = 1)

In [ ]:
def score_category(score):
    if score < 70:
        return 'Low'
    elif score <= 85:
        return 'Average'
    else:
        return 'High'

ScoresData['score_category'] = ScoresData['average_score'].apply(score_category)

In [ ]:
print("Feature Engineered Data Preview:")
display(ScoresData[['name', 'age', 'average_score', 'score_category']].head())

Feature Engineered Data Preview:

              name  age  average_score score_category
0  James Schneider   18      80.884058        Average
1   Kristina Weeks   17      75.152778        Average
2  Danielle Norman   16      83.866667        Average
3     Susan Morgan   17      82.884058        Average
4     Erika Wilson   17      73.333333        Average

**FINAL STUDENT SCORE DATASET**

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
scaler = StandardScaler()
z_scores = scaler.fit_transform(ScoresData[['math_score', 'english_score', 'science_score']])

ScoresData['math_zscore'] = z_scores[:, 0]
ScoresData['english_zscore'] = z_scores[:, 1]
ScoresData['science_zscore'] = z_scores[:, 2]

In [ ]:
from sklearn.preprocessing import MinMaxScaler

In [ ]:
minmax_scaler = MinMaxScaler()
minmax_scaled = minmax_scaler.fit_transform(ScoresData[['math_score', 'english_score', 'science_score']])

ScoresData['math_minmax'] = minmax_scaled[:, 0]
ScoresData['english_minmax'] = minmax_scaled[:, 1]
ScoresData['science_minmax'] = minmax_scaled[:, 2]

In [ ]:
display(ScoresData)

,id,name,gender,birth_date,math_score,english_score,science_score,birth_year,age,average_score,score_category,math_zscore,english_zscore,science_zscore,math_minmax,english_minmax,science_minmax
0,1,James Schneider,Male,2007-02-23,88.000000,76.0,78.652174,2007,18,80.884058,Average,0.804255,-0.283796,0.000000,0.756757,0.444444,0.464531
1,2,Kristina Weeks,Male,2008-07-03,80.458333,75.0,70.000000,2008,17,75.152778,Average,0.000000,-0.392948,-0.865042,0.552928,0.416667,0.236842
2,3,Danielle Norman,Female,2009-01-02,87.000000,78.6,86.000000,2009,16,83.866667,Average,0.697614,0.000000,0.734634,0.729730,0.516667,0.657895
3,4,Susan Morgan,Female,2008-12-06,97.000000,73.0,78.652174,2008,17,82.884058,Average,1.764030,-0.611253,0.000000,1.000000,0.361111,0.464531
4,5,Erika Wilson,Female,2008-12-26,70.000000,60.0,90.000000,2008,17,73.333333,Average,-1.115293,-2.030232,1.134552,0.270270,0.000000,0.763158
5,6,Deborah Ford,Male,2008-10-30,62.000000,90.0,99.000000,2008,17,83.666667,Average,-1.968426,1.244336,2.034370,0.054054,0.833333,1.000000
6,7,Craig Johnson,Female,2006-11-12,80.458333,89.0,96.000000,2006,19,88.486111,High,0.000000,1.135184,1.734431,0.552928,0.805556,0.921053
7,8,Derek Lee,Female,2006-12-30,77.000000,78.0,91.000000,2006,19,82.000000,Average,-0.368802,-0.065491,1.234532,0.459459,0.500000,0.789474
8,9,Michael Ward,Male,2009-07-29,93.000000,87.0,66.000000,2009,16,82.000000,Average,1.337463,0.916879,-1.264961,0.891892,0.750000,0.131579
9,10,Carlos Nash,Male,2008-06-28,78.000000,78.6,78.652174,2008,17,78.417391,Average,-0.262161,0.000000,0.000000,0.486486,0.516667,0.464531
10,11,Lisa Spencer,Female,2009-10-15,80.458333,96.0,78.652174,2009,16,85.036836,High,0.000000,1.899249,0.000000,0.552928,1.000000,0.464531
11,12,Dawn Bell,Male,2007-06-19,77.000000,84.0,71.000000,2007,18,77.333333,Average,-0.368802,0.589422,-0.765062,0.459459,0.666667,0.263158
12,13,Brandy Booth,Male,2008-03-15,68.000000,78.6,78.652174,2008,17,75.084058,Average,-1.328577,0.000000,0.000000,0.216216,0.516667,0.464531
13,14,Angela Gay,Female,2007-07-13,80.458333,61.0,85.000000,2007,18,75.486111,Average,0.000000,-1.921080,0.634654,0.552928,0.027778,0.631579
14,15,Jared Ruiz,Female,2009-05-03,77.000000,71.0,68.000000,2009,16,72.000000,Average,-0.368802,-0.829557,-1.065001,0.459459,0.305556,0.184211
15,16,Corey Grimes,Male,2007-12-23,87.000000,91.0,71.000000,2007,18,83.000000,Average,0.697614,1.353488,-0.765062,0.729730,0.861111,0.263158
16,17,Amanda Williams,Female,2009-12-06,84.000000,78.0,67.000000,2009,16,76.333333,Average,0.377689,-0.065491,-1.164981,0.648649,0.500000,0.157895
17,18,Christina Collins,Female,2009-08-30,93.000000,64.0,67.000000,2009,16,74.666667,Average,1.337463,-1.593623,-1.164981,0.891892,0.111111,0.157895
18,19,Christopher Cuevas,Male,2007-09-17,75.000000,78.0,73.000000,2007,18,75.333333,Average,-0.582085,-0.065491,-0.565103,0.405405,0.500000,0.315789
19,20,Shannon Byrd,Female,2008-09-09,62.000000,80.0,82.000000,2008,17,74.666667,Average,-1.968426,0.152813,0.334715,0.054054,0.555556,0.552632
20,21,Kristen Eaton,Male,2007-07-30,86.000000,65.0,78.000000,2007,18,76.333333,Average,0.590972,-1.484471,-0.065204,0.702703,0.138889,0.447368
21,22,Joel Carlson,Female,2008-12-30,84.000000,86.0,91.000000,2008,17,87.000000,High,0.377689,0.807727,1.234532,0.648649,0.722222,0.789474
22,23,Robert Allen,Female,2008-11-13,60.000000,88.0,61.000000,2008,17,69.666667,Low,-2.181709,1.026031,-1.764859,0.000000,0.777778,0.000000
23,24,Chelsea Bell,Male,2009-09-28,80.458333,76.0,80.000000,2009,16,78.819444,Average,0.000000,-0.283796,0.134755,0.552928,0.444444,0.500000
24,25,Jeremy Johnson,Male,2007-07-14,77.000000,91.0,78.652174,2007,18,82.217391,Average,-0.368802,1.353488,0.000000,0.459459,0.861111,0.464531
25,26,Barbara Clark,Male,2007-12-19,94.000000,73.0,78.652174,2007,18,81.884058,Average,1.444105,-0.611253,0.000000,0.918919,0.361111,0.464531
26,27,Jay Wilkins,Male,2006-11-23,88.000000,78.6,70.000000,2006,19,78.866667,Average,0.804255,0.000000,-0.865042,0.756757,0.516667,0.236842
27,28,Wendy Baker,Female,2009-05-23,80.458333,88.0,65.000000,2009,16,77.819444,Average,0.000000,1.026031,-1.364940,0.552928,0.777778,0.105263
28,29,Daniel Crawford,Female,2007-07-29,75.000000,78.6,84.000000,2007,18,79.200000,Average,-0.582085,0.000000,0.534674,0.405405,0.516667,0.605263
29,30,Lauren Long,Male,2007-09-15,92.000000,67.0,98.000000,2007,18,85.666667,High,1.230822,-1.266166,1.934390,0.864865,0.194444,0.973684

In [ ]:
ScoresData.to_csv('encoded_student_scores.csv', index = False)
print("Processed file saved as 'encoded_student_scores.csv'")

Processed file saved as 'encoded_student_scores.csv'

In [ ]:
from google.colab import files
files.download("encoded_student_scores.csv")